import { unified } from 'unified';
import remarkParse from 'remark-parse';
import remarkGfm from 'remark-gfm';
import GithubSlugger from 'github-slugger';

export interface TocItem {
  id: string;
  title: string;
  pages?: TocItem[];
}

// Minimal structural shape of the mdast nodes we actually read — avoids
// pulling in @types/mdast just for this.
interface MdastNode {
  type: string;
  depth?: number;
  value?: string;
  children?: MdastNode[];
}

function headingText(node: MdastNode): string {
  if (typeof node.value === 'string') return node.value;
  if (!node.children) return '';
  return node.children.map(headingText).join('');
}

/**
 * Extracts H2/H3 headings from raw MDX for the "On this page" TOC, with
 * ids generated by github-slugger — the same package rehype-slug uses
 * internally at render time, so these anchors always match what's
 * actually on the page.
 */
export function extractHeadings(raw: string): TocItem[] {
  const tree = unified()
    .use(remarkParse)
    .use(remarkGfm)
    .parse(raw) as unknown as { children: MdastNode[] };

  const slugger = new GithubSlugger();
  const items: TocItem[] = [];
  let currentH2: TocItem | null = null;

  for (const node of tree.children) {
    if (node.type !== 'heading' || (node.depth !== 2 && node.depth !== 3)) {
      continue;
    }

    const title = headingText(node).trim();
    if (!title) continue;

    const item: TocItem = { id: slugger.slug(title), title };

    if (node.depth === 2) {
      items.push(item);
      currentH2 = item;
    } else if (currentH2) {
      currentH2.pages = [...(currentH2.pages ?? []), item];
    } else {
      // H3 with no preceding H2 in this doc — treat as top-level.
      items.push(item);
    }
  }

  return items;
}
